import { ArrowRight, BookOpen, CheckCircle2, PenLine, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const publishedGuides = [
  { href: "/guides/prompt-engineering-basics", title: "Prompt engineering basics", description: "A clear starting framework for writing useful AI instructions." },
  { href: "/guides/prompt-engineering-for-marketing", title: "Prompt engineering for marketing", description: "A practical method for building repeatable campaign briefs." },
  { href: "/guides/evaluate-and-improve-ai-prompts", title: "Evaluate and improve AI prompts", description: "A review process for clarity, consistency, and safer reuse." },
  { href: "/guides/promptforge-workflow-case-study", title: "PromptForge workflow case study", description: "A worked example from rough campaign idea to usable AI brief." },
];

export default function AuthorPage() {
  return <main className="simple-page author-page"><section className="page-intro editorial-intro author-hero"><div className="intro-side">AUTHOR PROFILE<br/><span>EDITORIAL TEAM</span></div><div><div className="author-brand-placeholder" role="img" aria-label="Placeholder organization logo for PromptForge"><span>PF</span></div><div className="eyebrow"><PenLine size={14}/> PROMPTFORGE EDITORIAL</div><h1>Practical AI guidance for people who make things.</h1><p>The PromptForge Editorial Team creates clear, workflow-led education about prompt engineering, AI-assisted content, and responsible reuse.</p><div className="author-profile-line"><div className="author-avatar-placeholder" role="img" aria-label="Placeholder avatar for PromptForge Editorial Team">PF</div><div><strong>PromptForge Editorial Team</strong><span>Prompt-engineering education and product guidance</span></div></div></div></section><section className="author-content"><div className="author-principles"><div className="section-kicker">EDITORIAL APPROACH <span>Useful before impressive.</span></div><div className="author-principle"><BookOpen size={19}/><div><h2>Teach the workflow</h2><p>Guides begin with a real task and show the decisions that make an AI brief clearer, more specific, and easier to review.</p></div></div><div className="author-principle"><CheckCircle2 size={19}/><div><h2>Keep examples honest</h2><p>Examples are labeled as demonstrations. We do not present invented customer results, reviews, or endorsements as evidence.</p></div></div><div className="author-principle"><ShieldCheck size={19}/><div><h2>Respect responsible use</h2><p>Content encourages human review, privacy-aware inputs, supportable claims, and extra care for regulated or high-stakes work.</p></div></div></div><aside className="author-contact-card"><div className="section-kicker">CORRECTIONS & IDEAS <span>Help us improve.</span></div><p>Found an unclear explanation or have a guide topic that would help your team? Send context and we’ll review it personally.</p><Link href="/contact" className="forge-button">Contact PromptForge <ArrowRight size={15}/></Link></aside></section><section className="author-guides"><div className="section-kicker">PUBLISHED GUIDES <span>Read the field guide.</span></div><div className="author-guide-grid">{publishedGuides.map((guide) => <Link href={guide.href} className="author-guide-card" key={guide.href}><strong>{guide.title}</strong><span>{guide.description}</span><ArrowRight size={15}/></Link>)}</div></section></main>;
}
